
    set(CLUCENE_VERSION_MAJOR 0)
    set(CLUCENE_VERSION_MINOR 9)
    set(CLUCENE_VERSION_REVISION 23)
    set(CLUCENE_VERSION_PATCH 0)
    
    set(CLUCENE_VERSION 0.9.23.0)
    set(CLUCENE_SOVERSION 0.9.23)
